### ISSUE TITLE
Set up the test pipeline for this project.

### ISSUE THREAD

**Issue by wammar** [higgood/med-jargon-explain-inator#16] opened 2024-05-10 23:02 UTC

**Comment by zepam** [comment] 2024-05-16 22:21
05/16: Yes, it would be nice to have CI/CD for this project, but I recommend we don't because:
* we have a limited amount of time and this would take too much time to set up
* we haven't released anything into production and we don't need to continually test new updates to make sure it works on all platforms
* would be more efficient to set up regression testing and only use that for now

**Comment by zepam** [comment] 2024-05-17 00:11
change 5/16:
working on a big CI/CD pipeline is out of scope for this project. It will be turned into developing a test pipeline instead.

**Comment by wammar** [comment] 2024-05-17 22:26
Deprioritizing the testing framework.

**Closed as completed** 2024-05-17 22:26 UTC
